In [2]:
# Statistics formula and their name:

In [3]:
Statistic syllabus:
    
    Mean
    
        > Arithmetic mean
        
        > Geometric mean
        
        > Harmonic mean
    
    median
    
        > odd term median
        
        > Even term median
        
    Mode:
        
        > single mode 
        
        > multimode
        
    Quantiles:
        
        >Q1
        
        >Q2
        
        >Q3
        
    IQR(Inter Quantiles Range)
    
        IQR=(Q3-Q1)
    
    Noise/error
    
        >Max_trend
    
        >Min_trend
    
    Graphs:
        
        > Uniform graph
        
        > Bell shape graph(Normal Graph)
        
        >Left scewed graph
        
        > Right scewed graph
            
    Unstructured data
    
    Numpy
        
        >scaler
        
        > Vector: 1D array, where D stand for Dimension
        
        > matrix: ND array , wehere ND stand for Numbers of Dimension
    
    Structured data

    Pandas:
        
        EDA (Exploratory Data Analysis)
        
        condition
        
        order by 
        
        group by 
        
        pivote table
    
    Visualization(data which we can see on graph)
        
        GUI:(Graphical User Interface)
            
            PowerBI(O 365)
                
                data clearning
                
                sorting
                
                graph
                
            
            Advance Excel(I will not teach, DAX operation)
            
        TUI:(Textual User Interface)
        
        > python
        
        > matlab
        



In [4]:
# Mean/ average/ percentage%
# There are three type of mean
# > Artithmetic mean(AM)
# > Geometric Mean(GM)
# > Harmonic Mean(HM)

In [ ]:
# > Artithmetic mean(AM)
     > When the values are in same range
# > Geometric Mean(GM)
     > when the values are in different range.
# > Harmonic Mean(HM)
     > when rate of change in data happend.

In [2]:
import statistics as st

In [3]:
a=6
b=4

In [5]:
st.mean((a,b))

5

In [6]:
st.mean(a,b)

TypeError: mean() takes 1 positional argument but 2 were given

In [7]:
st.geometric_mean((a,b))

4.898979485566356

In [8]:
st.harmonic_mean((a,b))

4.8

In [24]:
#arithmetic mean
def average(*n):
    return sum(n)/len(n)


In [25]:
average(4,6)

5.0

In [33]:
# geometric mean
def geometric(*n):
    cont=1
    for i in n:
        cont=cont*i
    return cont**(1/len(n))

In [34]:
geometric(4,6)

4.898979485566356

In [40]:
#harmonic mean
import numpy as np
def harmonic(*n):
    cont=0
    for i in n:
        cont=cont+1/i
    return np.round(len(n)/cont,decimals=2)

In [41]:
harmonic(4,6)

4.8

In [63]:
import numpy as np
class new_statistic:
  
    def harmonic(self,*n):
        cont=0
        for i in n:
            cont=cont+(1/i)
        return np.round(len(n)/cont,decimals=2)
    # geometric mean
    def geometric(self,*n):
        cont=1
        for i in n:
            cont=cont*i
        return cont**(1/len(n))
    #arithmetic mean
    def average(self,*n):
        return sum(n)/len(n)


In [64]:
st2=new_statistic()

In [65]:
st2.harmonic(4,6)

4.8

In [67]:
st2.geometric(4,6)

4.898979485566356

In [68]:
st2.harmonic(4,6)

4.8

In [2]:
Statistic syllabus:
    
    Mean
    
        > Arithmetic mean
        
        > Geometric mean
        
        > Harmonic mean
    
    median
    
        > odd term median
        
        > Even term median
        
    Mode:
        
        > single mode 
        
        > multimode
        
    Quantiles:
        
        >Q1
        
        >Q2
        
        >Q3
        
    IQR(Inter Quantiles Range)
    
        IQR=(Q3-Q1)
    
    Noise/error
    
        >Max_trend
    
        >Min_trend
    
    Graphs:
        
        > Uniform graph
        
        > Bell shape graph(Normal Graph)
        
        >Left scewed graph
        
        > Right scewed graph
            
    Unstructured data
    
    Numpy
        
        >scaler
        
        > Vector: 1D array, where D stand for Dimension
        
        > matrix: ND array , wehere ND stand for Numbers of Dimension
    
    Structured data

    Pandas:
        
        EDA (Exploratory Data Analysis)
        
        condition
        
        order by 
        
        group by 
        
        pivote table
    
    Visualization(data which we can see on graph)
        
        GUI:(Graphical User Interface)
            
            PowerBI(O 365)
                
                data clearning
                
                sorting
                
                graph
                
            
            Advance Excel(I will not teach, DAX operation)
            
        TUI:(Textual User Interface)
        
        > python
        
        > matlab
        

In [5]:
# Median--> there are two types of median --> odd term median, even term median

In [6]:
a=[2,3,4,3,4,3,4,6,87,3,2]

In [7]:
# odd term median=(n+1)/2

In [8]:
median=(11+1)/2
median

6.0

In [10]:
a.sort()

In [11]:
a

[2, 2, 3, 3, 3, 3, 4, 4, 4, 6, 87]

In [12]:
import statistics as st

In [13]:
st.median(a)

3

In [14]:
# even term Median=((n/2)th+((n/2)+1)th)/2

In [15]:
b=[3,2,4,5,6,3,5,6,8,8]

In [16]:
print(b)

[3, 2, 4, 5, 6, 3, 5, 6, 8, 8]


In [17]:
b.sort()

In [18]:
b

[2, 3, 3, 4, 5, 5, 6, 6, 8, 8]

In [19]:
# Mode ---> most occurring data in our dataset called mode

In [20]:
b

[2, 3, 3, 4, 5, 5, 6, 6, 8, 8]

In [21]:
st.mode(b)

3

In [22]:
st.multimode(b)

[3, 5, 6, 8]

In [1]:
import random

In [96]:
cont=[]
for i in range(10):
    cont.append(random.randint(1,10))
print(cont)
print("means",st.mean(cont))
quantiles=st.quantiles(cont)
q1,q2,q3=quantiles
print("q1:",q1)
print("q2:",q2)
print("q3:",q3)
print("sorted list:",cont.sort(),cont)
Max_trend=q3+1.5*(q3-q1)
print("Max Trend:",Max_trend)
Min_trend=q1-1.5*(q3-q1)
print("Min Trend :",Min_trend)
Max_trend_cont=[]
Min_trend_cont=[]
for i in cont:
    if i<Min_trend:
        Min_trend_cont.append(i)
    elif i>Max_trend:
        Max_trend_cont.append(i)
print("Min_trend_cont",Min_trend_cont)
print("Max_trend_cont",Max_trend_cont)

[1, 5, 5, 1, 5, 8, 5, 5, 5, 9]
means 4.9
q1: 4.0
q2: 5.0
q3: 5.75
sorted list: None [1, 1, 5, 5, 5, 5, 5, 5, 8, 9]
Max Trend: 8.375
Min Trend : 1.375
Min_trend_cont [1, 1]
Max_trend_cont [9]


In [40]:
import statistics as st

52.8

30.25
49.5
78.75


In [57]:
cont.sort()

In [58]:
cont

[22, 28, 31, 42, 46, 53, 54, 77, 84, 91]

-42.5

In [61]:
cont

[22, 28, 31, 42, 46, 53, 54, 77, 84, 91]

Unstructured data --> A dataset having no label called unstructured data.

> HTML table
> MS excel
> CSV(csv file is a plane text file)
> WML
> XML
>etc...

Structured data --> A dataset having label called structured data.
> MySQL
> SQL Server
> DB2
> SQLite 
> tabluler database. 

array: A datatype which contain similary type of data type called array,
ex: [1,2,3,4,5,6,7]
['a','krishna',"rohan"]
[1.2,3.2,43.2]

what is not acceptable in array:
[1,2,3,4,5,1.0]  it will return an error beacuse it has hetrogenous datatype


Numpy  : Numpy is a third party library so we have to install it using "pip install numpy" 
        
        >scaler
        
        > Vector: 1D array, where D stand for Dimension
        
        > matrix: ND array , wehere ND stand for Numbers of Dimension

In [3]:
pip install numpy

In [4]:
import numpy as np

In [6]:
np.array([1,2,3,4,5])  # 1 D array (Dimension)

array([1, 2, 3, 4, 5])

In [8]:
np.array(1)   # scaler array having 0 Dimension

array(1)

In [10]:
np.array([[2,1,2],[3,2,1],[1,1,1]])

array([[2, 1, 2],
       [3, 2, 1],
       [1, 1, 1]])

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])

In [4]:
print(a)

[1 2 3 4 5 6]


In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [16]:
a=range(10)
a

range(0, 10)

In [15]:
b=np.arange(0,10,1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
import sys
sys.getsizeof(a)

48

In [18]:
sys.getsizeof(b)

152

In [19]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [21]:
range(0,10,0.2)

TypeError: 'float' object cannot be interpreted as an integer

In [22]:
a=np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.array(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.random.randint(1,10,(2,5))

array([[5, 4, 7, 1, 3],
       [6, 8, 2, 2, 8]])

In [51]:
np.zeros((5,2),dtype=np.str_)

array([['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [53]:
np.ones((2,2),dtype=np.str_)

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [48]:
np.full((2,3,2),5)

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [55]:
np.array([1,2,3,"10"],dtype=np.int16)

array([ 1,  2,  3, 10], dtype=int16)

In [57]:
np.array([1,2,3,"krishna"])

array(['1', '2', '3', 'krishna'], dtype='<U11')

In [58]:
# string
# float
# int
# to change precedence we use dtype=np.int

In [60]:
np.full((2,10),100.0)

array([[100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.]])

In [61]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [1]:
np.linspace(0,100,19)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
np.random.randint(1,10,(10))

array([8, 1, 9, 8, 2, 2, 5, 6, 2, 2])

In [6]:
np.random.randint(1,10,(2,3))

array([[1, 2, 1],
       [4, 6, 9]])

In [8]:
np.random.randint(1,10,(2,2,2,2))

array([[[[2, 9],
         [6, 8]],

        [[7, 4],
         [4, 6]]],


       [[[1, 6],
         [3, 2]],

        [[8, 3],
         [4, 3]]]])

In [9]:
np.random.randint(1,10)

8

In [10]:
# flatten

In [11]:
a=np.random.randint(1,10,(2,2,2,2))

In [12]:
a

array([[[[6, 1],
         [5, 9]],

        [[5, 3],
         [1, 1]]],


       [[[8, 1],
         [2, 2]],

        [[8, 5],
         [3, 8]]]])

In [14]:
a.flatten(order="C")

array([6, 1, 5, 9, 5, 3, 1, 1, 8, 1, 2, 2, 8, 5, 3, 8])

In [15]:
a.flatten(order="F")

array([6, 8, 5, 8, 5, 2, 1, 3, 1, 1, 3, 5, 9, 2, 1, 8])

In [17]:
b=np.array([i for i in range(10)])

In [18]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
b.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
b.reshape((2,2))

ValueError: cannot reshape array of size 10 into shape (2,2)

In [26]:
b.resize((2,2),refcheck=False)

In [27]:
print(b)

[[0 1]
 [2 3]]


In [28]:
print(b)

[[0 1]
 [2 3]]


In [29]:
b.flatten()

array([0, 1, 2, 3])

In [33]:
c=np.arange(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
c.resize((2,2,3))

In [35]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [37]:
c.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
c.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
d=c.reshape(6,-1)
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
np.sum(d,axis=0)   # axis =0 use to add values column wise

array([30, 36])

In [50]:
np.sum(d,axis=1)  # axis =1 is use to add values row wise

array([ 1,  5,  9, 13, 17, 21])

In [52]:
np.mean(d,axis=0)

array([5., 6.])

In [53]:
np.mean(d,axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5])

In [59]:
c.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
np.min(d,axis=0)

array([0, 1])

In [64]:
np.max(d,axis=1)

array([ 1,  3,  5,  7,  9, 11])

In [65]:
np.median(d)

5.5

In [67]:
np.median(d,axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5])

In [68]:
np.median(d,axis=0)

array([5., 6.])

In [69]:
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [72]:
a=np.array([3,2,4,6,7,8,4,2])

In [73]:
print(a)

[3 2 4 6 7 8 4 2]


In [76]:
np.argmax(a)

5

In [77]:
np.argmin(a)

1

In [78]:
a

array([3, 2, 4, 6, 7, 8, 4, 2])

In [81]:
np.sort(a)

array([2, 2, 3, 4, 4, 6, 7, 8])

In [84]:
np.sort(d)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [87]:
a=np.random.randint(1,100,(2,3))
a

array([[55, 94, 42],
       [63, 11, 44]])

In [90]:
np.sort(a,axis=0)

array([[55, 11, 42],
       [63, 94, 44]])

In [92]:
np.sort(a,axis=1)

array([[42, 55, 94],
       [11, 44, 63]])

In [1]:
import numpy as np

In [11]:
a=np.linspace(1,10,(100))

In [12]:
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [15]:
np.round(a,decimals=2)

array([ 1.  ,  1.09,  1.18,  1.27,  1.36,  1.45,  1.55,  1.64,  1.73,
        1.82,  1.91,  2.  ,  2.09,  2.18,  2.27,  2.36,  2.45,  2.55,
        2.64,  2.73,  2.82,  2.91,  3.  ,  3.09,  3.18,  3.27,  3.36,
        3.45,  3.55,  3.64,  3.73,  3.82,  3.91,  4.  ,  4.09,  4.18,
        4.27,  4.36,  4.45,  4.55,  4.64,  4.73,  4.82,  4.91,  5.  ,
        5.09,  5.18,  5.27,  5.36,  5.45,  5.55,  5.64,  5.73,  5.82,
        5.91,  6.  ,  6.09,  6.18,  6.27,  6.36,  6.45,  6.55,  6.64,
        6.73,  6.82,  6.91,  7.  ,  7.09,  7.18,  7.27,  7.36,  7.45,
        7.55,  7.64,  7.73,  7.82,  7.91,  8.  ,  8.09,  8.18,  8.27,
        8.36,  8.45,  8.55,  8.64,  8.73,  8.82,  8.91,  9.  ,  9.09,
        9.18,  9.27,  9.36,  9.45,  9.55,  9.64,  9.73,  9.82,  9.91,
       10.  ])

In [8]:
# broadcasting

In [22]:
a=[1,2,3,4,5]
b=[3,4,5,6,7]
print(a+b)

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]


In [25]:
cont=[]
for i,j in zip(a,b):
    cont.append(i+j)
print(cont)

# method2
cont2=[i+j for i,j in zip(a,b)]
cont2

[4, 6, 8, 10, 12]


[4, 6, 8, 10, 12]

In [28]:
c=np.array([1,2,3,4,5])
d=np.array([3,4,5,6,7])
print(c+d)

[ 4  6  8 10 12]


In [29]:
c-d

array([-2, -2, -2, -2, -2])

In [30]:
c*d

array([ 3,  8, 15, 24, 35])

In [31]:
print(d)

[3 4 5 6 7]


In [32]:
d/2

array([1.5, 2. , 2.5, 3. , 3.5])

In [33]:
d

array([3, 4, 5, 6, 7])

In [34]:
d*2

array([ 6,  8, 10, 12, 14])

In [35]:
d-2

array([1, 2, 3, 4, 5])

In [36]:
d+2

array([5, 6, 7, 8, 9])

In [37]:
d

array([3, 4, 5, 6, 7])

In [38]:
e=np.array([[2,2],[3,3]])
e

array([[2, 2],
       [3, 3]])

In [39]:
f=np.array([[3,3,3],[6,6,6]])
f

array([[3, 3, 3],
       [6, 6, 6]])

In [40]:
np.dot(e,f)

array([[18, 18, 18],
       [27, 27, 27]])

In [41]:
e@f

array([[18, 18, 18],
       [27, 27, 27]])

In [46]:
e.T

array([[2, 3],
       [2, 3]])

In [47]:
e

array([[2, 2],
       [3, 3]])

In [48]:
e.transpose()

array([[2, 3],
       [2, 3]])